### ISSUE TITLE
Issue during Sync

### ISSUE THREAD

**Issue by OneWingedAng3l** [SSENSE/node-cucumber-testrail-sync#11]
Hello and congratulations for your work. I was really looking for a tool like this.
Though i have the following issue. I have followed the process as you describe in your doc but when i run the command to sync between the TR and my Cucumber tests i get the following error:

> $box: ~/node_modules/.bin/cucumber-testrail-sync
> undefined:1
> File not found.
> ^
> 
> SyntaxError: Unexpected token F in JSON at position 0
>     at Object.parse (native)
>     at Request._callback (/Users/usr/node_modules/testrail-api/index.js:78:30)
>     at Request.self.callback (/Users/usr/node_modules/request/request.js:188:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (/Users/usr/node_modules/request/request.js:1171:10)
>     at emitOne (events.js:96:13)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (/Users/usr/node_modules/request/request.js:1091:12)
>     at IncomingMessage.g (events.js:291:16)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

my configuration is the following:

```
module.exports = {
    testrail: {
        host: 'https://testrail.someurl.com/testrail/index.php',
        user: 'user',
        password: 'pass',  // password or api key
        filters: {
            plan_id: '10' // required: the project's plan id
        }
    }
};
```

Can you help a bit ?

**Comment by rundef** [comment]
Hello, the `host` in the config should not contain any path/filename: 

`host: 'https://testrail.someurl.com'`

**Comment by OneWingedAng3l** [comment]
Hello, i have tried that as well but i get the same response :(

**Comment by OneWingedAng3l** [comment]
Hello, the issue has been resolved. It was on my side since for some reason they would not me to access the api. Thanks again!
