### ISSUE TITLE
Is there a way to integrate this with grunt?

### ISSUE THREAD

**Issue by glui2001** [SSENSE/node-cucumber-testrail-sync#12]
The documentation seems to only indicate manual execution.  I originally wanted to push the results to TestRail, but the syncing features looks really cool!

I have Chimp (using cucumber) running and exporting a JSON reports file.

Please advise.

**Comment by rundef** [comment]
Hi,
You can use something like [grunt-exec](https://github.com/jharding/grunt-exec) to run commands.

**Comment by glui2001** [comment]
How about the manual push (https://github.com/SSENSE/node-cucumber-testrail-sync/blob/master/docs/pushing_results.md)?  Does that require some grunt execution?  Or does the `hook.js` auto run in the context of cucumber to push the file?

**Comment by rundef** [comment]
Once you setup the `hooks.js` file, all you have to do is to run the tests with the `--push` flag: `./node_modules/.bin/cucumber-testrail-sync --push`

**Comment by rundef** [comment]
Once you setup `hooks.js`, results will be pushed when you run the cucumber tests if you set `pushResults: true` in your config file.

**Comment by glui2001** [comment]
Couple of questions since I'm unable to do this successfully:

1. I'm running cucumber through Chimp.  Will this still work?  Have you guys tried it?
2. My "pushResults" property in `.testrail-sync.js` looks like this.  It is at the root of my repo.  Whereas the ".feature" files are in some sub-folders (<root>/tests/automation/features).  Is this correct?
```
module.exports = {
  testrail: {
    host: 'https://xxx.testrail.com',
    user: 'xxx',
    password: 'xxx',  // password or api key
    pushResults: true,
    filters: {
       plan_id: '2407'
```
3. I installed "hooks.js" into "<root>/tests/automation/features/support" (cucumber's context?).  Hooks.js is set for cucumber 1.x

Please advise. Thank you.

**Comment by rundef** [comment]
1. No we didn't try it. From what I can see, Chimp is used to test UIs but `cucumber.js` still run the tests, right ? If so, it will work.
2. Yes. But were the `.feature` files synced with this module ? Basically, the sync process creates `@tcid:xyz` tags in each `.feature` file where xyz is the id of the testcase in TestRail.
Then after each test are ran, the module looks for the value of the `@tcid` tag and push the test result of that testcase id to TestRail. If the tag doesn't exist, the module has no way to link the test with the correct TestRail's testcase.
