### ISSUE TITLE
Background, not supported

### ISSUE THREAD

**Issue by asenlog** [SSENSE/node-cucumber-testrail-sync#13]
Hello,
 I am trying to sync some tests from TestRail to my local machine but i am getting the following message:

> Syncing with TestRail ...
> 
> Invalid gherkin content for TestCase #43491-invalid-login
>   Background:
>       Given I am on login page

Is the keyword "Background Supported" ? If not how should i handle the preconditions ?

Thank you,

Regards,
Angelos

**Comment by asenlog** [comment]
Hello again,
   Will you support this ?

Thank you,

Regards,
Angelos

**Comment by rundef** [comment]
Hi, sorry for the delay.
Yes, I should be able to look into it this week.

**Comment by asenlog** [comment]
Awesome ! Thanks! I really need it :)

**Comment by mbround18** [comment]
Hello @rundef, is there an available fix for this?

**Comment by rundef** [comment]
@mbround18 No, I'm no longer in charge of this project, so I cannot help you. Sorry.
